### ISSUE TITLE
DOM evaluation slow

### ISSUE THREAD

**Issue by ryangjchandler** [alpine-collective/alpinejs-devtools#10]
Each time I open and close the inspector / devtools, the DOM is being re-evaluated and is quite slow to interact. 

Might be worth looking into another approach for watching and tracking Alpine components.

**Comment by HugoDF** [comment]
Might be useful to hook into the proxy so that already detected and tracked components don't get re-crawled

**Comment by ryangjchandler** [comment]
> Might be useful to hook into the proxy so that already detected and tracked components don't get re-crawled

Yeah that's how I tackled it in my extension. I would have also liked the core events too so that you can just registering change event listeners on the component. 

If I put my 90% done extension in a repo I can share with you both.

**Comment by Te7a-Houdini** [comment]
@ryangjchandler that would be helpful

**Comment by HugoDF** [comment]
Where did we get to on this one?

**Comment by HugoDF** [comment]
As part of this https://github.com/Te7a-Houdini/alpinejs-devtools/pull/21

I noticed that we evaluate/parse data from the whole DOM before initialising the devtools panel, maybe we should just be getting `x-data` attributes to populate the component list and then when a component is clicked we parse/eval the specifics for that?

**Comment by Te7a-Houdini** [comment]
@HugoDF it maybe a good idea . we should try it

**Comment by HugoDF** [comment]
A good example of sluggish perf is https://alpinetoolbox.com probably a good place to look at what our bottleneck is.

**Comment by HugoDF** [comment]
Update: 

The sluggishness could be a JSON.stringify/messaging thing which #46 was starting to address (ie. instead of getting all the data on boot, get just the component names and fetch the relevant component data when the component is selected).

#108 is also changing the way components are observed (should mean we have 1 observer per page vs 1 per component).

It would be great if someone could spend the time adding some `console.time`/`console.timeEnd` into the extension and run it against https://alpinetoolbox.com/ (for example) to see where the bottleneck is.
