### ISSUE TITLE
Appears to hang if no components found

### ISSUE THREAD

**Issue by KevinBatdorf** [alpine-collective/alpinejs-devtools#130]
It should probably have a "nothing found" state, or even just end the loading animation, if we are keeping that.

(I'm starting a new project so no components yet)

<img width="1567" alt="Screen Shot 2020-12-16 at 1 49 55 PM" src="https://user-images.githubusercontent.com/1478421/102314886-c1e38800-3fa5-11eb-82f1-e513b807374b.png">

**Comment by HugoDF** [comment]
This is what I came up with feel free to PR/push onto that PR.

Note that this only happens if Alpine is on the page but there are not components 😄 .

<img width="1076" alt="Screenshot 2020-12-16 at 09 34 51" src="https://user-images.githubusercontent.com/6459679/102331386-b03cb900-3f82-11eb-8876-6f1ac60cdcda.png">

**Comment by KevinBatdorf** [comment]
Looks fine to me. Yeah I just started a project and this page has no components, but I just load Alpine in globally anyway :)
