### ISSUE TITLE
Support for Alpine V3

### ISSUE THREAD

**Issue by aguillen-js** [alpine-collective/alpinejs-devtools#244]
Alpine devtools don't recognize components when using the latest version of Alpine (V3). Maybe I'm missing something.

![Screenshot 2021-06-16 212113](https://user-images.githubusercontent.com/5055390/122315915-f26e9500-cee8-11eb-994e-551be030fcb3.png)

**Comment by stephenoldham** [comment]
@aguillen-js Just out of interest what browser and OS are you using? I'll see if I can declutter the auto scrollbar styles.

**Comment by HugoDF** [comment]
So I had a quick look at how we might support V3

Core functionality (current):

- [x] get initial data
- [x] watch for data changes
- [x] edit data
- [ ] catch eval errors


Future functionality:

- [ ] Stores/global data support
- [ ] `$dispatch` support

## Get initial data

```js
const xData = document.querySelector('[x-data]')._x_dataStack[0]
const dataKeys = Object.keys(xData).filter(name => !name.startsWith('$'))
```

## Watch for data changes

```js
const xData = document.querySelector('[x-data]')._x_dataStack[0]
const dataKeys = Object.keys(xData).filter(name => !name.startsWith('$'))

// add an x-effect that sends us back the data
// @todo: how to deal with an x-data that already has an x-effect, is it fine to `{existing};hook(aa);` it? Probably not, might be better to insert a new element and do it that way
document.querySelector('[x-data]').setAttribute('x-effect', `console.log({${dataKeys.join(',')}})`)
```

## Edit data

```js
const xData = document.querySelector('[x-data]')._x_dataStack[0]

xData.count = 120
```


## Catch eval errors

Changes required to Alpine core (so that errors are emitted with the right information).

Currently `alpine-next` doesn't even log a warning.

**Comment by aguillen-js** [comment]
> @aguillen-js Just out of interest what browser and OS are you using? I'll see if I can declutter the auto scrollbar styles.

@stephenoldham Hello, I am using Windows 10. Regarding the browser, when I do web development I have Chrome, Firefox Developer Edition and Edge running, I like to check everything in the most recent version of each browser. The screenshot in question was taken from Chrome.
